module.exports = {
  apps: [
    {
      name: 'kabin247',
      script: './build/bin/server.js',
      cwd: '/root/Kabin247',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        PORT: 3333,
        HOST: '127.0.0.1',
        DB_HOST: '127.0.0.1',
        DB_PORT: 3306,
        DB_USER: 'kabin247',
        DB_PASSWORD: 'kabin247',
        DB_DATABASE: 'app',
        APP_KEY: 'c2pRFTsYeFmsBcik6e2puKwdFor53U1j',
        LOG_LEVEL: 'info',
        SESSION_DRIVER: 'cookie',
        DRIVE_DISK: 'fs',
        SMTP_USERNAME: 'your_smtp_username',
        SMTP_PASSWORD: 'your_smtp_password',
        SMTP_HOST: 'smtp.example.com',
        SMTP_PORT: '587',
        SMTP_EMAIL: 'your_email@example.com',
      },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
    },
    {
      name: 'adminjs',
      script: './node_modules/.bin/tsx',
      args: 'adminjs-server.ts',
      cwd: '/root/Kabin247',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        ADMINJS_PORT: 3001,
        DB_HOST: '127.0.0.1',
        DB_PORT: 3306,
        DB_USER: 'kabin247',
        DB_PASSWORD: 'kabin247',
        DB_DATABASE: 'app',
      },
      error_file: './logs/adminjs-error.log',
      out_file: './logs/adminjs-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
    },
  ],
}

